version: '3.9'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app
      - ignore:/usr/app/node_modules/
  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - .:/postgresql
volumes:
  ignore:
    